version: '3.3'

networks:
  default:
    driver: bridge

services:

  flask:
    build: .docker/flask
    container_name: flask
    ports:
      - '5000:5000'
    volumes: 
      - ./http:/app
    networks:
      - default

  crawler:
    build: 
      context: .docker/python
      dockerfile: ./Dockerfile
      args:
      - FOLDER=crawler
    container_name: crawler
    volumes: 
      - ./crawler:/usr/src/app
    networks:
      - default

  crawler_by_id:
    build: 
      context: .docker/python
      dockerfile: ./Dockerfile
      args:
      - FOLDER=crawler_by_id
    container_name: crawler_by_id
    volumes: 
      - ./crawler_by_id:/usr/src/app
    networks:
      - default

  parser:
    build: 
      context: .docker/python
      dockerfile: ./Dockerfile
      args:
      - FOLDER=parser
    container_name: parser
    volumes: 
      - ./parser:/usr/src/app
    networks:
      - default

  front:
    image: nginx
    container_name: front
    restart: 'no'
    ports:
      - '80:80'
    volumes:
      - .docker/nginx:/etc/nginx/conf.d
      - ./front/build:/var/www
    networks:
      - default
  
